FORM = "FORM"
FORM_CHAR = "FORM_CHAR"
LEMMA_CHAR = "LEMMA_CHAR"
UPOS = "UPOS"
DEPREL = "DEPREL"
FEATS = "FEATS"
HEAD = "HEAD"

X   = [FORM, FORM_CHAR]
Y   = [LEMMA_CHAR, UPOS, FEATS, HEAD, DEPREL]
ALL = [FORM, FORM_CHAR, LEMMA_CHAR, UPOS, FEATS, HEAD, DEPREL]